#!/bin/sh

chmod +x /usr/libexec/rpcd/luci.nss-status
chmod +x /usr/libexec/rpcd/luci.ecm-status
chmod +x /usr/libexec/rpcd/luci.nss-dashboard

chmod +x /etc/init.d/nss-tuning
/etc/init.d/nss-tuning enable

chmod +x /usr/lib/sqm/nss-helper.sh

chmod +x /etc/init.d/sqm-nss
/etc/init.d/sqm-nss enable

chmod +x /etc/init.d/wifi-nss-tuning
/etc/init.d/wifi-nss-tuning enable

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache /tmp/rpcd

uci set luci.main.mediaurlbase='/luci-static/openwrt2020'
uci commit luci

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache /tmp/rpcd

exit 0
