#!/bin/sh

chmod +x /usr/libexec/rpcd/luci.nss-status
chmod +x /usr/libexec/rpcd/luci.ecm-status

chmod +x /etc/init.d/nss-tuning
/etc/init.d/nss-tuning enable

chmod +x /usr/lib/sqm/nss-helper.sh

chmod +x /etc/init.d/sqm-nss
/etc/init.d/sqm-nss enable

chmod +x /usr/libexec/rpcd/luci.nss-dashboard

chmod +x /etc/init.d/wifi-nss-tuning
/etc/init.d/wifi-nss-tuning enable

rm -f /tmp/luci-indexcache

exit 0
