#!/bin/sh /etc/rc.common

START=15

start() {
	logger -t NSS-TUNING 'Applying ECM limits'

	[ -e /sys/kernel/debug/ecm/ecm_nss_ipv4/driver_fail_limit_default ] && \
		echo 0 > /sys/kernel/debug/ecm/ecm_nss_ipv4/driver_fail_limit_default

	[ -e /sys/kernel/debug/ecm/ecm_nss_ipv4/no_action_limit_default ] && \
		echo 250 > /sys/kernel/debug/ecm/ecm_nss_ipv4/no_action_limit_default

	[ -e /sys/kernel/debug/ecm/ecm_nss_ipv4/nack_limit_default ] && \
		echo 250 > /sys/kernel/debug/ecm/ecm_nss_ipv4/nack_limit_default

	logger -t NSS-TUNING 'done'
}
