#!/bin/sh /etc/rc.common

START=20

start() {
	logger -t WIFI-NSS 'Applying ath11k NSS offload'

	if [ -w /sys/module/ath11k/parameters/nss_offload ]; then
		echo 1 > /sys/module/ath11k/parameters/nss_offload
		logger -t WIFI-NSS 'nss_offload=1'
	else
		logger -t WIFI-NSS 'nss_offload sysfs not writable'
	fi
}
