#!/bin/sh /etc/rc.common

START=20

apply_irq()
{
	for irq in $(grep ath11k /proc/interrupts | awk '{print $1}' | tr -d ':')
	do
		echo 2 > /proc/irq/$irq/smp_affinity
	done
}


start()
{
	logger -t WIFI-NSS "Starting ath11k NSS tuning"

	# enable NSS offload if available

	if [ -e /sys/module/ath11k/parameters/nss_offload ]
	then
		echo 1 > /sys/module/ath11k/parameters/nss_offload
	fi


	# IRQ balance

	apply_irq


	logger -t WIFI-NSS "ath11k NSS tuning completed"
}
